//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_KhoPBVaThuocBVTV.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietKiemKe
    {
        public int MaCTKiemKe { get; set; }
        public Nullable<int> MaKiemKe { get; set; }
        public Nullable<int> MaSP { get; set; }
        public Nullable<int> SoLuongTheoSo { get; set; }
        public Nullable<int> SoLuongThucTe { get; set; }
        public Nullable<int> ChenhLech { get; set; }
        public string GhiChu { get; set; }
    
        public virtual KiemKeKho KiemKeKho { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
