//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_KhoPBVaThuocBVTV.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhGiaSanPham
    {
        public int MaDanhGia { get; set; }
        public Nullable<int> MaSP { get; set; }
        public Nullable<int> DiemDanhGia { get; set; }
        public string NoiDung { get; set; }
        public Nullable<System.DateTime> NgayDanhGia { get; set; }
        public Nullable<int> NguoiDanhGia { get; set; }
        public Nullable<int> NguoiTao { get; set; }
        public Nullable<int> NguoiCapNhat { get; set; }
        public Nullable<int> MaKH { get; set; }
    
        public virtual NguoiDung NguoiDung { get; set; }
        public virtual NguoiDung NguoiDung1 { get; set; }
        public virtual NguoiDung NguoiDung2 { get; set; }
        public virtual SanPham SanPham { get; set; }
        public virtual KhachHang KhachHang { get; set; }
    }
}
