//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_KhoPBVaThuocBVTV.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DuDoanNhapHang
    {
        public int MaDuDoan { get; set; }
        public Nullable<int> MaPhieuNhap { get; set; }
        public Nullable<System.DateTime> NgayDuDoan { get; set; }
        public Nullable<int> SoLuongDuDoan { get; set; }
        public Nullable<decimal> DoChinhXac { get; set; }
        public string MucDich { get; set; }
        public string CanCuVao { get; set; }
        public string GhiChu { get; set; }
    
        public virtual PhieuNhapKho PhieuNhapKho { get; set; }
    }
}
