//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_KhoPBVaThuocBVTV.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kho
    {
        public Kho()
        {
            this.KiemKeKhoes = new HashSet<KiemKeKho>();
            this.PhieuNhapKhoes = new HashSet<PhieuNhapKho>();
            this.PhieuXuatKhoes = new HashSet<PhieuXuatKho>();
            this.SanPhams = new HashSet<SanPham>();
        }
    
        public int MaKho { get; set; }
        public string TenKho { get; set; }
        public string DiaChi { get; set; }
        public int MaND { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
    
        public virtual NguoiDung NguoiDung { get; set; }
        public virtual ICollection<KiemKeKho> KiemKeKhoes { get; set; }
        public virtual ICollection<PhieuNhapKho> PhieuNhapKhoes { get; set; }
        public virtual ICollection<PhieuXuatKho> PhieuXuatKhoes { get; set; }
        public virtual ICollection<SanPham> SanPhams { get; set; }
    }
}
