//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_KhoPBVaThuocBVTV.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class KiemKeKho
    {
        public KiemKeKho()
        {
            this.ChiTietKiemKes = new HashSet<ChiTietKiemKe>();
        }
    
        public int MaKiemKe { get; set; }
        public string SoPhieu { get; set; }
        public System.DateTime NgayKiemKe { get; set; }
        public Nullable<int> MaKho { get; set; }
        public Nullable<int> MaND { get; set; }
        public string TrangThai { get; set; }
        public string GhiChu { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
    
        public virtual ICollection<ChiTietKiemKe> ChiTietKiemKes { get; set; }
        public virtual Kho Kho { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
    }
}
