//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_KhoPBVaThuocBVTV.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LichSuHoatDong
    {
        public int MaLichSu { get; set; }
        public Nullable<int> MaND { get; set; }
        public System.DateTime ThoiGian { get; set; }
        public string LoaiHoatDong { get; set; }
        public string ChiTiet { get; set; }
        public Nullable<int> NguoiTao { get; set; }
        public Nullable<int> NguoiCapNhat { get; set; }
    
        public virtual NguoiDung NguoiDung { get; set; }
        public virtual NguoiDung NguoiDung1 { get; set; }
        public virtual NguoiDung NguoiDung2 { get; set; }
    }
}
