//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_KhoPBVaThuocBVTV.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class NguoiDung
    {
        public NguoiDung()
        {
            this.DangNhaps = new HashSet<DangNhap>();
            this.DanhGiaSanPhams = new HashSet<DanhGiaSanPham>();
            this.DanhGiaSanPhams1 = new HashSet<DanhGiaSanPham>();
            this.DanhGiaSanPhams2 = new HashSet<DanhGiaSanPham>();
            this.Khoes = new HashSet<Kho>();
            this.KiemKeKhoes = new HashSet<KiemKeKho>();
            this.LichSuDatLaiMatKhaus = new HashSet<LichSuDatLaiMatKhau>();
            this.LichSuDatLaiMatKhaus1 = new HashSet<LichSuDatLaiMatKhau>();
            this.LichSuGias = new HashSet<LichSuGia>();
            this.LichSuGias1 = new HashSet<LichSuGia>();
            this.LichSuGias2 = new HashSet<LichSuGia>();
            this.LichSuHoatDongs = new HashSet<LichSuHoatDong>();
            this.LichSuHoatDongs1 = new HashSet<LichSuHoatDong>();
            this.LichSuHoatDongs2 = new HashSet<LichSuHoatDong>();
            this.PhieuNhapKhoes = new HashSet<PhieuNhapKho>();
            this.PhieuXuatKhoes = new HashSet<PhieuXuatKho>();
            this.YeuCauDatLaiMatKhaus = new HashSet<YeuCauDatLaiMatKhau>();
            this.YeuCauDatLaiMatKhaus1 = new HashSet<YeuCauDatLaiMatKhau>();
        }
    
        public int MaND { get; set; }
        public byte[] AnhDaiDien { get; set; }
        public string HoTen { get; set; }
        public string SoCCCD { get; set; }
        public string Email { get; set; }
        public string SoDienThoai { get; set; }
        public string DiaChi { get; set; }
        public System.DateTime NgaySinh { get; set; }
        public string GioiTinh { get; set; }
        public string VaiTro { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
    
        public virtual ICollection<DangNhap> DangNhaps { get; set; }
        public virtual ICollection<DanhGiaSanPham> DanhGiaSanPhams { get; set; }
        public virtual ICollection<DanhGiaSanPham> DanhGiaSanPhams1 { get; set; }
        public virtual ICollection<DanhGiaSanPham> DanhGiaSanPhams2 { get; set; }
        public virtual ICollection<Kho> Khoes { get; set; }
        public virtual ICollection<KiemKeKho> KiemKeKhoes { get; set; }
        public virtual ICollection<LichSuDatLaiMatKhau> LichSuDatLaiMatKhaus { get; set; }
        public virtual ICollection<LichSuDatLaiMatKhau> LichSuDatLaiMatKhaus1 { get; set; }
        public virtual ICollection<LichSuGia> LichSuGias { get; set; }
        public virtual ICollection<LichSuGia> LichSuGias1 { get; set; }
        public virtual ICollection<LichSuGia> LichSuGias2 { get; set; }
        public virtual ICollection<LichSuHoatDong> LichSuHoatDongs { get; set; }
        public virtual ICollection<LichSuHoatDong> LichSuHoatDongs1 { get; set; }
        public virtual ICollection<LichSuHoatDong> LichSuHoatDongs2 { get; set; }
        public virtual ICollection<PhieuNhapKho> PhieuNhapKhoes { get; set; }
        public virtual ICollection<PhieuXuatKho> PhieuXuatKhoes { get; set; }
        public virtual ICollection<YeuCauDatLaiMatKhau> YeuCauDatLaiMatKhaus { get; set; }
        public virtual ICollection<YeuCauDatLaiMatKhau> YeuCauDatLaiMatKhaus1 { get; set; }
    }
}
