//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_KhoPBVaThuocBVTV.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhanTichBanHang
    {
        public int MaPhanTich { get; set; }
        public Nullable<int> MaSP { get; set; }
        public Nullable<System.DateTime> ThoiGian { get; set; }
        public Nullable<int> SoLuongBan { get; set; }
        public Nullable<decimal> DoanhThu { get; set; }
        public string XuHuong { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
    
        public virtual SanPham SanPham { get; set; }
    }
}
