//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_KhoPBVaThuocBVTV.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QL_KHOPhanBonThuocBVTVEntities : DbContext
    {
        public QL_KHOPhanBonThuocBVTVEntities()
            : base("name=QL_KHOPhanBonThuocBVTVEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ChiTietKiemKe> ChiTietKiemKes { get; set; }
        public DbSet<ChiTietPhieuNhap> ChiTietPhieuNhaps { get; set; }
        public DbSet<ChiTietPhieuXuat> ChiTietPhieuXuats { get; set; }
        public DbSet<DangNhap> DangNhaps { get; set; }
        public DbSet<DanhGiaSanPham> DanhGiaSanPhams { get; set; }
        public DbSet<DuDoanNhapHang> DuDoanNhapHangs { get; set; }
        public DbSet<Kho> Khoes { get; set; }
        public DbSet<KiemKeKho> KiemKeKhoes { get; set; }
        public DbSet<LichSuDatLaiMatKhau> LichSuDatLaiMatKhaus { get; set; }
        public DbSet<LichSuGia> LichSuGias { get; set; }
        public DbSet<LichSuHoatDong> LichSuHoatDongs { get; set; }
        public DbSet<LoaiSanPham> LoaiSanPhams { get; set; }
        public DbSet<NguoiDung> NguoiDungs { get; set; }
        public DbSet<NhaCungCap> NhaCungCaps { get; set; }
        public DbSet<PhanTichBanHang> PhanTichBanHangs { get; set; }
        public DbSet<PhieuNhapKho> PhieuNhapKhoes { get; set; }
        public DbSet<PhieuXuatKho> PhieuXuatKhoes { get; set; }
        public DbSet<SanPham> SanPhams { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<YeuCauDatLaiMatKhau> YeuCauDatLaiMatKhaus { get; set; }
    }
}
