//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_KhoPBVaThuocBVTV.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        public SanPham()
        {
            this.ChiTietKiemKes = new HashSet<ChiTietKiemKe>();
            this.ChiTietPhieuNhaps = new HashSet<ChiTietPhieuNhap>();
            this.ChiTietPhieuXuats = new HashSet<ChiTietPhieuXuat>();
            this.DanhGiaSanPhams = new HashSet<DanhGiaSanPham>();
            this.LichSuGias = new HashSet<LichSuGia>();
            this.PhanTichBanHangs = new HashSet<PhanTichBanHang>();
        }
    
        public int MaSP { get; set; }
        public string MaQR { get; set; }
        public byte[] AnhSP { get; set; }
        public string TenSP { get; set; }
        public Nullable<int> MaLoai { get; set; }
        public Nullable<int> MaNCC { get; set; }
        public Nullable<int> MaKho { get; set; }
        public string DonViTinh { get; set; }
        public Nullable<int> SoLuongTon { get; set; }
        public decimal DonGia { get; set; }
        public Nullable<System.DateTime> NgaySanXuat { get; set; }
        public Nullable<System.DateTime> HanSuDung { get; set; }
        public string CachSuDung { get; set; }
        public string XuatXu { get; set; }
        public string MoTa { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
    
        public virtual ICollection<ChiTietKiemKe> ChiTietKiemKes { get; set; }
        public virtual ICollection<ChiTietPhieuNhap> ChiTietPhieuNhaps { get; set; }
        public virtual ICollection<ChiTietPhieuXuat> ChiTietPhieuXuats { get; set; }
        public virtual ICollection<DanhGiaSanPham> DanhGiaSanPhams { get; set; }
        public virtual Kho Kho { get; set; }
        public virtual ICollection<LichSuGia> LichSuGias { get; set; }
        public virtual LoaiSanPham LoaiSanPham { get; set; }
        public virtual NhaCungCap NhaCungCap { get; set; }
        public virtual ICollection<PhanTichBanHang> PhanTichBanHangs { get; set; }
    }
}
