//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_KhoPBVaThuocBVTV.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class YeuCauDatLaiMatKhau
    {
        public YeuCauDatLaiMatKhau()
        {
            this.LichSuDatLaiMatKhaus = new HashSet<LichSuDatLaiMatKhau>();
        }
    
        public int MaYeuCau { get; set; }
        public Nullable<int> MaND { get; set; }
        public string LyDo { get; set; }
        public string ThongTinXacNhan { get; set; }
        public string MatKhauMoi { get; set; }
        public string TrangThai { get; set; }
        public Nullable<System.DateTime> NgayYeuCau { get; set; }
        public Nullable<System.DateTime> NgayXuLy { get; set; }
        public Nullable<int> NguoiXuLy { get; set; }
        public string GhiChu { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
    
        public virtual ICollection<LichSuDatLaiMatKhau> LichSuDatLaiMatKhaus { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
        public virtual NguoiDung NguoiDung1 { get; set; }
    }
}
